name: safe_bloom
description: "Safe Bloom — Your Cycle. Your Privacy. Your Power."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite_sqlcipher: ^3.0.0
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  path: ^1.9.0
  local_auth: ^2.3.0
  fl_chart: ^0.70.0
  pdf: ^3.11.1
  printing: ^5.13.4
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/safe-bloom-logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
